### ISSUE TITLE
Review uncompleted work

### ISSUE THREAD

**Issue by juanjoseortega-aircury** [curacultura/curacultura-website#57]
Check uncompleted pages, maybe add "Work in progress", till i get translations
- The mention of the non existent Google doc won't be removed (Client knows about this mention, but doesn't want to get it removed because it will be ready soon).
- Fix the projects link in the offering page.
- Fix images in the projects page in Spanish.
- Remove French and Italian from language switcher

**Comment by cristobaldiaz-aircury** [comment]
More uncompleted work to be covered:

1. The mention of a non existent Google doc in the main page.
2. The projects link (https://curacultura.com/tabs/projects.md) in the offerings page (https://curacultura.com/tabs/offering.html) doesn't lead anywhere.
3. In the projects page in Spanish (https://curacultura.com/es/tabs/projects.html) the images cannot be seen.

Please confirm this with the client before making any changes.
