### ISSUE TITLE
Design proposals low effort

### ISSUE THREAD

**Issue by juanjoseortega-aircury** [curacultura/curacultura-website#68]
1. Navigation bar **(Estimated Work Time: 15m to 30m)**
- Modify the search button, let it open and put it in the bottom right corner.
- Remove icons from the menu.
2. All pages **(Estimated Work Time: 30m to 1h)**
- Move the arrow to the bottom right corner.
- Use a different font for titles, it shouldn’t be that much different from the logo.
  - A similar font to the logo can be used, therefore not requiring much client input.
3. Projects page **(Estimated Work Time: 15m to 30m)**
- Add a background to categories with border radius (can be different colours for each category).
4. About page
-Make some tweaks to the shape of the profile pictures.
**Total Estimated Work Time: 2h**

**Comment by cristobaldiaz-aircury** [comment]
This part from point 3 is already implemented, right?

> - Make closer the project image to the text from the right.
> - Review space between elements:
>    - Images too far from the rest.
>    - Texts too close to each other.
