### ISSUE TITLE
Review SEO

### ISSUE THREAD

**Issue by juanjoseortega-aircury** [curacultura/curacultura-website#89]
Review SEO and improve it if possible.
**Tasks:**
- Add token to check the metrics at google search console.
- Add sitemaps file
- Check SEO with Seobility
**TODO:**
- Add more content/words at "About page" 

Pages used for check SEO:
- [Seobility](https://www.seobility.net/es/seochecker/)
- [SiteChecker](https://sitechecker.pro/)

**Comment by cristobaldiaz-aircury** [comment]
We should get this fixed as part of another ticket:
![Image](https://github.com/curacultura/curacultura-website/assets/105167930/249f6cb6-56e3-4197-9af2-1550fc64cb20)
